development:
  adapter: postgresql
  encoding: unicode
  database: projectp
  pool: 5
  username: projectp
  password: projectp

test:
  adapter: postgresql
  encoding: unicode
  database: projectp
  pool: 5
  username: projectp
  password: projectp